include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "lib/firebase_options.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: warning
    missing_required_param: error
    missing_return: error
    deprecated_member_use_from_same_package: warning
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_int_literals: false
    always_specify_types: true
    omit_local_variable_types: false
